name: Auto Commit

on:
  schedule:
    - cron: "0 23 * * *" # 매일 오전 8시 (UTC 기준으로 23시)
  workflow_dispatch: # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 클론
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. 파일 업데이트 (현재 날짜 추가)
      - name: Update File
        run: |
          echo "$(date)" >> grass-log.txt

      # 3. 변경사항 커밋
      - name: Commit Changes
        run: |
          git config --local user.name "YourGitHubUsername" # 사용자명 설정
          git config --local user.email "YourGitHubEmail@example.com" # 이메일 설정
          git add .
          git commit -m "Automated commit on $(date)" || echo "No changes to commit"

      # 4. 변경사항 푸시
      - name: Push Changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
