name: Auto Commit

on:
  schedule:
    - cron: "0 2 * * *" # UTC 기준 오전 2시 (KST 오전 11시)
  workflow_dispatch: # 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update File with KST Time
        run: |
          MESSAGES=("Stay positive!" "Keep going!" "You are doing great!" "One step at a time." "Believe in yourself.")
          RANDOM_INDEX=$((RANDOM % ${#MESSAGES[@]}))
          KST_DATE=$(TZ=Asia/Seoul date +"%Y-%m-%d %H:%M:%S")
          RANDOM_NUMBER=$((RANDOM))

          echo "$KST_DATE: ${MESSAGES[$RANDOM_INDEX]} - Random: $RANDOM_NUMBER" >> grass-log.txt
          echo "$KST_DATE: Meaningful update added." >> grass-log.txt

      - name: Commit Changes
        run: |
          git config --global user.name "isyouhyeong"
          git config --global user.email "isyouh77@gmail.com"
          git add .
          git commit -m "Auto-commit: Updated grass-log.txt on $KST_DATE" || echo "No changes to commit"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
