name: Auto Commit

on:
  schedule:
    - cron: "0 23 * * *" # 매일 오전 8시 (UTC 기준으로 23시)
  workflow_dispatch: # 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 클론
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. 파일 업데이트 (다양한 정보 추가)
      - name: Update File with Random Message and Repo Info
        run: |
          # 랜덤 메시지 설정
          MESSAGES=("Stay positive!" "Keep going!" "You are doing great!" "One step at a time." "Believe in yourself.")
          RANDOM_INDEX=$((RANDOM % ${#MESSAGES[@]}))
          
          # 브랜치 및 커밋 수 정보 추가
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          COMMIT_COUNT=$(git rev-list --count HEAD)
          
          # grass-log.txt에 정보 기록
          echo "$(date): ${MESSAGES[$RANDOM_INDEX]}" >> grass-log.txt
          echo "$(date): Branch $BRANCH has $COMMIT_COUNT commits." >> grass-log.txt

      # 3. 변경사항 커밋
      - name: Commit Changes
        run: |
          git config --global user.name "your-github-username" # 사용자명
          git config --global user.email "your-email@example.com" # 이메일
          git add .
          git commit -m "Daily update on $(date +'%Y-%m-%d %H:%M:%S'): Updated log file" || echo "No changes to commit"

      # 4. 변경사항 푸시
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
