name: Auto Commit

on:
  schedule:
    - cron: "0 23 * * *" # UTC 기준 매일 23시 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 클론
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. 파일 업데이트 (다양한 정보 추가)
      - name: Update File with Random Message and Repo Info
        run: |
          MESSAGES=("Stay positive!" "Keep going!" "You are doing great!" "One step at a time." "Believe in yourself.")
          RANDOM_INDEX=$((RANDOM % ${#MESSAGES[@]}))
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          COMMIT_COUNT=$(git rev-list --count HEAD)
          UTC_DATE=$(date -u "+%Y-%m-%d %H:%M:%S UTC") # UTC 시간 기록

          echo "$UTC_DATE: ${MESSAGES[$RANDOM_INDEX]}" >> grass-log.txt
          echo "$UTC_DATE: Branch $BRANCH has $COMMIT_COUNT commits." >> grass-log.txt

      # 3. 변경사항 커밋
      - name: Commit Changes
        run: |
          git config --global user.name "isyouhyeong" # 사용자명
          git config --global user.email "162817850+isyouhyeong@users.noreply.github.com" # 이메일
          git add .
          git commit -m "Daily update on $(date -u +'%Y-%m-%d %H:%M:%S UTC'): Updated log file" || echo "No changes to commit"

      # 4. 변경사항 푸시
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
